def nextVersion //x.y.z
def Version //x.y
pipeline{
    agent any

    tools { 
        maven 'maven:3.6.2' 
        jdk 'jdk8' 
    }
    stages {
        stage('calculate tag'){
            when {
                branch "release/*"
            }
            steps {
                script {
                    sh 'git fetch --all --tags'
                        Version = (env.GIT_BRANCH  =~ /(\d+\.\d+)$/)[0][1]
                        def baseVersion = "${Version}"
                        def lastVersion = sh(script: "git tag | grep '^${baseVersion}' | sort -V | tail -n 1", returnStdout: true).trim()
                        println "Last version of ${baseVersion}: ${lastVersion}"
                        if (lastVersion == "") {
                            nextVersion = "${baseVersion}.0"
                        } else {
                            def versionParts = lastVersion.split("\\.")
                            def lastVersionNumber = Integer.parseInt(versionParts[-1])
                            nextVersion = "${baseVersion}.${lastVersionNumber + 1}"
                        }
                    sh "mvn versions:set -DnewVersion=${nextVersion}"
                    sh "mvn versions:commit"
                }
            }
        }
        stage('version'){
            steps{
                script{
                    withCredentials([usernamePassword(credentialsId: 'artifactory-username-password', passwordVariable: 'password', usernameVariable: 'username')]) {
                        ANALYTICS = sh(returnStdout: true, script: 'wget -r -np -nH --cut-dirs 4 --user=$username --password=$password http://artifactory:8081/artifactory/libs-release-local/com/lidar/analytics/').trim()
                        TELEMETRY = sh(returnStdout: true, script: 'wget -r -np -nH --cut-dirs 4 --user=$username --password=$password http://artifactory:8081/artifactory/libs-release-local/com/lidar/telemetry/').trim()
                        telemetry_folder = sh(returnStdout: true, script: "cd ./telemetry/ && ls -d */ | grep ${Version} | head -1").trim()
                        analytics_folder = sh(returnStdout: true, script: "cd ./analytics/ && ls -d */ | grep ${Version} | head -1").trim()
                        
                        sh 'echo "${telemetry_folder}"'
                        sh 'echo "${analytics_folder}"'
                        sh 'echo "${Version}"'

                        if (telemetry_folder == ""){
                            error("telemetry and product versions do not match")
                        }
                        if (analytics_folder == ""){
                            error("analytics and product versions do not match")
                        }

                        latest_telemetry_clean = sh(returnStdout: true, script:"basename ${telemetry_folder} '/'").trim()
                        latest_analytics_clean = sh(returnStdout: true, script:"basename ${analytics_folder} '/'").trim()

                        telemetry_path = "./telemetry/${latest_telemetry_clean}/telemetry-${latest_telemetry_clean}.jar"
                        analytics_path = "./analytics/${latest_analytics_clean}/analytics-${latest_analytics_clean}.jar"
                        
                        echo "telemetry_path ---> ${telemetry_path}"
                        echo "analytics_path ---> ${analytics_path}"

                        sh "mvn versions:set-property -DnewVersion='${latest_telemetry_clean}' -Dproperty=telemetry.version"
                        sh "mvn versions:set-property -DnewVersion='${latest_analytics_clean}' -Dproperty=analytics.version"
                        sh "mvn versions:set -DnewVersion=${nextVersion}"
                        sh "mvn dependency:list"
                        sh "mvn versions:commit"
                    }
                }
            }
        }
        
        stage('build & unit tests'){
            when {
                anyOf {
                    branch "release/*"
                }
            }
            steps {
                configFileProvider([configFile(fileId: 'global-mavem-xml', variable: 'MAVEN_SETTINGS_XML')]) {
                    sh "mvn -s $MAVEN_SETTINGS_XML clean package"
                }
            }
        }
        stage('e2e tests'){
            when {
                anyOf {
                    branch "release/*"
                } 
            }
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: 'artifactory-username-password', passwordVariable: 'password', usernameVariable: 'username')]) {
                        sh 'wget -r -np -nH --cut-dirs 4 --user=$username --password=$password http://artifactory:8081/artifactory/libs-snapshot-local/com/lidar/simulator/99-SNAPSHOT/'
                    }
                    latest_simulator_snapshot= sh(returnStdout: true, script: 'ls -t ./simulator/99-SNAPSHOT/simulator-99*.jar | head -1').trim()
                    sh "cp ${latest_simulator_snapshot} simulator.jar"
                    file_to_uzip = sh(returnStdout: true, script: "cd ./target/ && ls | sort -V | tail -1").trim()
                    sh "unzip ./target/${file_to_uzip}"
                    latest_analytic= sh(returnStdout: true, script: 'ls | grep analytics-').trim()
                    sh "java -cp ./simulator.jar:./telemetry-${latest_telemetry_clean}.jar:./analytics-${latest_analytics_clean}.jar com.lidar.simulation.Simulator"
                }
            }
        }
        stage('deploy'){
            when {
                anyOf{
                    branch "release/*"                
                }
            }
            steps {
                configFileProvider([configFile(fileId: 'global-mavem-xml', variable: 'MAVEN_SETTINGS_XML')]) {
                    sh "mvn -s $MAVEN_SETTINGS_XML clean deploy -DskipTests"
                }
            }
        }
        stage('tag release'){
            when {
                branch "release/*"
            }
            steps{
                withCredentials([usernamePassword(credentialsId: 'Gitlab-username-and-password', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                    sh 'git remote set-url origin "http://${GIT_USERNAME}:${GIT_PASSWORD}@gitlab/ofir-dev/product.git"'
                    sh "git tag -a ${nextVersion} -m '[ci-skip]'"
                    sh "git push origin ${nextVersion}"
                }
        }
    }
}
post{
        always{
            echo "========always========"
            cleanWs()
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}

